### ISSUE TITLE
BACKEND: Build a Drivable Generic Expressway

### ISSUE THREAD

**Issue by TomCC7** [UmichSIM/SIM_MDP_GUI#38]
Updated related to freeway experiments are updated and tracked here. Refer to [this link](https://docs.google.com/document/d/1sHcV5BD81kAhPGfGsIXNT0usxqpCpSeT) for a description of the goal.

Tasks:

+ [x] figure out what we have and what we don't have
+ [ ] #50
+ [ ] #52
+ [ ] Vehicles (non-subject) avoid crashing when too close with subject vehicle
+ [ ] Record simulation and steering wheel control data (More information in goals document)
+ [ ] Visual occlusion option

**Tasks** (Merging with frontend):
+ [ ] Change vehicle configuration_dictionary to add vehicles, sections, and section paths

**Comment by TomCC7** [comment]
@djunru Can I ask you to mainly work on this task? Since you worked on it during Summer lol

**Comment by djunru** [comment]
Tasks (Not Completed):
- [ ] Initialize with vehicles acting as speed barriers
- [ ] Configure speed and lane change of vehicles (non-subject) at certain points in simulation 
- [ ] Vehicles (non-subject) avoid crashing when too close with subject vehicle
- [ ] Record simulation and steering wheel control data (More information in goals document)
- [ ] Visual occlusion option
Tasks (Merging with frontend):
- [ ] Change vehicle configuration_dictionary to add vehicles, sections, and section paths
